//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAether.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReAether.Data.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;components&quot;: {
        ///		&quot;0&quot;: {&quot;index&quot;: 0, &quot;texture&quot;: 0},
        ///		&quot;1&quot;: {&quot;index&quot;: 0, &quot;texture&quot;: 0},
        ///		&quot;2&quot;: {&quot;index&quot;: 4, &quot;texture&quot;: 0},
        ///		&quot;3&quot;: {&quot;index&quot;: 11, &quot;texture&quot;: 0},
        ///		&quot;4&quot;: {&quot;index&quot;: 74, &quot;texture&quot;: 0},
        ///		&quot;5&quot;: {&quot;index&quot;: 0, &quot;texture&quot;: 0},
        ///		&quot;6&quot;: {&quot;index&quot;: 9, &quot;texture&quot;: 0},
        ///		&quot;7&quot;: {&quot;index&quot;: -1, &quot;texture&quot;: 0},
        ///		&quot;8&quot;: {&quot;index&quot;: -1, &quot;texture&quot;: 0},
        ///		&quot;9&quot;: {&quot;index&quot;: -1, &quot;texture&quot;: 0},
        ///		&quot;10&quot;: {&quot;index&quot;: 0, &quot;texture&quot;: 0},
        ///		&quot;11&quot;: {&quot;index&quot;: 15, &quot;texture&quot;: 0},
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string CommonsUniform {
            get {
                return ResourceManager.GetString("CommonsUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PopCatVehicleList {
            get {
                return ResourceManager.GetString("PopCatVehicleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 abigail1
        ///abigail2
        ///achievement_controller
        ///act_cinema
        ///activity_creator_prototype_launcher
        ///af_intro_t_sandy
        ///agency_heist1
        ///agency_heist2
        ///agency_heist3a
        ///agency_heist3b
        ///agency_prep1
        ///agency_prep2amb
        ///aicover_test
        ///ainewengland_test
        ///altruist_cult
        ///am_agency_suv
        ///am_airstrike
        ///am_ammo_drop
        ///am_arena_shp
        ///am_armwrestling_apartment
        ///am_armwrestling
        ///am_armybase
        ///am_backup_heli
        ///am_beach_washup_cinematic
        ///am_boat_taxi
        ///am_bru_box
        ///am_car_mod_tut
        ///am_casino_limo
        ///am_casino_luxury_car
        ///am_casino_peds
        ///am_chal [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Scripts {
            get {
                return ResourceManager.GetString("Scripts", resourceCulture);
            }
        }
    }
}
